
////
This file is generated! See _meta/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Phpfpmbeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-cloud>>
* <<exported-fields-phpfpmbeat>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== beat.version

The version of the beat that generated this event.


[float]
=== @timestamp

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-cloud]]
== Cloud Provider Metadata Fields

Metadata from cloud providers added by the add_cloud_metadata processor.



[float]
=== meta.cloud.provider

example: ec2

Name of the cloud provider. Possible values are ec2, gce, or digitalocean.


[float]
=== meta.cloud.instance_id

Instance ID of the host machine.


[float]
=== meta.cloud.machine_type

example: t2.medium

Machine type of the host machine.


[float]
=== meta.cloud.availability_zone

example: us-east-1c

Availability zone in which this host is running.


[float]
=== meta.cloud.project_id

example: project-x

Name of the project in Google Cloud.


[float]
=== meta.cloud.region

Region in which this host is running.


[[exported-fields-phpfpmbeat]]
== phpfpmbeat Fields

Contains PHP-FPM status, data is collected from PHP-FPM status page.


[float]
=== pool

type: keyword

Name of the PHP-FPM pool.


[float]
=== process_manager

type: keyword

Process manager mode: "static", "dynamic" or "ondemand".


[float]
=== start_since

type: long

Number of seconds since FPM has started or reloaded. Reloading PHP-FPM will reset this value.


[float]
=== accepted_conn

type: long

Number of requests accepted by the pool.


[float]
=== listen_queue

type: long

Number of requests in the queue of pending connections.


[float]
=== max_listen_queue

type: long

Maximum number of requests in the queue of pending connections since FPM has started.


[float]
=== listen_queue_len

type: long

Size of the socket queue of pending connections.


[float]
=== idle_processes

type: long

Number of idle processes.


[float]
=== active_processes

type: long

Number of active processes.


[float]
=== total_processes

type: long

Number of idle + active processes.


[float]
=== max_active_processes

type: long

Maximum number of active processes since FPM has started.


[float]
=== max_children_reached

type: long

Number of times the process limit has been reached (when FPM tries to start more children). Only works with "dynamic" and "ondemand" pool types.


[float]
=== slow_requests

type: long

Number of requests that exceeded your request_slowlog_timeout value.


