
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported Fields

This document describes the fields that are exported by
Topbeat. They are grouped in the
following categories:

* <<exported-fields-env>>
* <<exported-fields-phpfpm>>

[[exported-fields-env]]
=== Common Fields

Contains common fields available in all event types.



==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the measurements were taken. The precision is in milliseconds. The timezone is UTC.


==== type

required: True

Set to "phpfpm" to specify that this is PHP-FPM status.


==== count

type: int

required: True

For how many transactions is this event representative. This is generally the inverse of the sampling rate. For example, for a sample rate of 1/10, the count is 10. The count is used by the UIs to return estimated values. Reserved for future usage.


==== beat.name

Name of the Beat sending the events. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


==== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[[exported-fields-phpfpm]]
=== PHP-FPM status Fields

Contains PHP-FPM status, data is collected from PHP-FPM status page.



==== pool

type: string

The name of the PHP-FPM pool.


==== process_manager

type: string

The process manager mode: "static", "dynamic" or "ondemand".


==== start_since

type: int

The number of seconds since FPM has started or reloaded. Reloading PHP-FPM will reset this value.


==== accepted_conn

type: int

The number of requests accepted by the pool.


==== listen_queue

type: int

The number of requests in the queue of pending connections.


==== max_listen_queue

type: int

The maximum number of requests in the queue of pending connections since FPM has started.


==== listen_queue_len

type: int

The size of the socket queue of pending connections.


==== idle_processes

type: int

The number of idle processes.


==== active_processes

type: int

The number of active processes.


==== total_processes

type: int

The number of idle + active processes.


==== max_active_processes

type: int

The maximum number of active processes since FPM has started.


==== max_children_reached

type: int

The number of times the process limit has been reached (when FPM tries to start more children). Only works with "dynamic" and "ondemand" pool types.


==== slow_requests

type: int

The number of requests that exceeded your request_slowlog_timeout value.


